# Generated by Django 3.2.12 on 2023-02-18 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('body', models.CharField(default='', max_length=1000000)),
                ('created_at', models.DateTimeField(blank=1, default=datetime.datetime.now)),
            ],
        ),
    ]
